name: pipeline-scan

on:

  push:
      branches: [ "main" ]
  pull_request:
      # The branches below must be a subset of the branches above
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: maven clean verify
  pipeline-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download the Pipeline Scanner
        uses: wei/curl@master
        with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
       
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and copies all sources into ZIP file for submitting for analysis. Replace this section with your applications build steps
      - uses: actions/checkout@v3
        with:
          repository: ''

      - run: zip -r veracode-scan-target.zip ./
    
      - name: Unzip the Pipeline Scanner
        run: unzip pipeline-scan-LATEST.zip
        
      - name: Run Pipeline Scanner
        run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file veracode-scan-target.zip
