name: Main Branch Workflow

on:

  push:

      branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1

      with:

        java-version: 1.8

    - name: Cache Maven packages

      uses: actions/cache@v2

      with:

        path: ~/.m2

        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

    - name: Build with Maven

      run: mvn clean package

      

    - uses: actions/upload-artifact@v1

      with:

        name: verademo.war

        path: target/verademo.war

        

  veracode-pipeline-scan:

    runs-on: ubuntu-latest

    needs: build

    container:

      image: veracode/pipeline-scan:latest

      options: --user root

    steps:

      - name: get archive

        uses: actions/download-artifact@v2

        with:

          name: verademo.war

          path: /tmp

      - name: Pipeline Scan

        run: |

          java -jar /opt/veracode/pipeline-scan.jar \

            -vid "${{ secrets.VERACODE_API_ID }}" \

            -vkey "${{ secrets.VERACODE_API_KEY }}" \

            --fail_on_severity="Very High, High" \

            --file /tmp/verademo.war \

            -jf results.json

            -fjf filtered_results.json

        continue-on-error: true

      - name: save standard results

        uses: actions/upload-artifact@v1

        with:

          name: PipelineScanResults

          path: results.json

      - name: save filtered results

        uses: actions/upload-artifact@v1

        with:

          name: filtered-results

          path: filtered_results.json
